### ISSUE TITLE
Add a certificate script for Rocket League (Opensuse)

### ISSUE THREAD

**Issue by Mirppc** [steamtricks/steamtricks#42]
There is an issue with connecting to the Rocket League servers on Opensuse (Tumbleweed, 13.2 and Leap).  This has something to do with a certificate issue that isn't related to the common Openssl issue.

There is a fix mentioned in the Opensuse Forums on how to fix the issue with connecting to the Rocket League servers everytime one updates their system or when rocket league gets and update.  Could it be included in steamtricks?

https://forums.opensuse.org/showthread.php/522490-Cannot-connect-to-servers-on-Rocket-League

**Comment by boombatower** [comment]
I do not own rocket league. Can you provide a list of files and a copy of it's startup script? I'll assume the appid and app_name information from store is correct `252950`, `Rocket_League`. Does this apply to other games? If so perhaps a global fix. I am not sure if this would be better suited as a proper package on obs that steamtricks requests to be installed or even a general change to suse's certificates package.

The script from the forum would probably benefit from checking to see if the file already exists or is symlinked. Likely if it exists is enough since perhaps the user has a reason for not linking to the same file. If the file does not exist then prompt for sudo and make the link.

While writing this I decided to look at [ca-certificates](https://build.opensuse.org/package/view_file/Base:System/ca-certificates/ca-certificates.spec?expand=1) package and it seems it is linking the file into the directory just above for compatibility. As such it seems like minor tweak to also link into `/certs`. I'll submit that and see what is said. If accepted we can look into back-porting to Leap.

EDIT: ca-certificates setup is a bit funky and being stubborn trying to add, but I'll keep poking at it.

**Comment by boombatower** [comment]
Well that was far trickier than it should have been. Anyway, https://build.opensuse.org/request/show/495507.

**Comment by boombatower** [comment]
@Mirppc Could confirm the fix works by removing `/etc/ssl/certs/ca-certificates.crt` and then installing the package from the source repo of mine?

**Comment by boombatower** [comment]
Was rejected on grounds that make sense. With that the suggestion was to try and preload the system openssl may workaround the issue. Without a copy of the game I'm working blind, but if you using `ldd rocket_league_binary` and `LD_PRELOAD one should be able to attempt that.

**Comment by boombatower** [comment]
I built the alternative that was reluctantly suggested. This is really a completely incorrect usage by rocket league.

The [package is in the steamtricks repo](https://build.opensuse.org/package/show/home:boombatower:steamtricks/ca-certificates-steamtricks) for now, but I will submit to Factory if it resolves the issue.
```
zypper in ca-certificates-steamtricks
```

If so I'll make it a dependency of rocket league.

**Comment by boombatower** [comment]
As of 570b42b009f9962dade2400c0d3d861a8c9ae22a steamtricks should attempt to install `steamtricks-data-$app_id-${app_name// /_}` or `steamtricks-data-252950-Rocket_League` which I updated `ca-certificates-steamtricks` to provide since there is nothing else requiring a full package. As such if you run _head_ and have refresh steamtricks repo it should be auto installed if you re-validate rocket league after deleting a file from it's game directory.

**Comment by boombatower** [comment]
I also updated the steamtricks package in the steamtricks repo if you use it out of there run the following to test out the fix after updating and restarting steam.

```
steamtricks apply 252950
```

**Comment by boombatower** [comment]
The package creates the file and unless rocket league generates a package name different from what I expect the fix should be installed. If not the provide in package can be updated. As such I will close this.
